### ISSUE TITLE
NoClassDefFoundError: groovy.lang.Closure

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/LPhyBeast#101]
After deploying lphybeast as a BEAST 2 package, it returns err:

```java
Caused by: java.lang.NoClassDefFoundError: groovy.lang.Closure
	at beast.pkgmgmt.MultiParentURLClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at picocli.CommandLine$DefaultFactory.loadClosureClass(CommandLine.java:5477)
	at picocli.CommandLine$DefaultFactory.<clinit>(CommandLine.java:5475)
	at picocli.CommandLine.<init>(CommandLine.java:196)
	at lphybeast.LPhyBeastCMD.main(LPhyBeastCMD.java:83)
```

**Comment by walterxie** [comment]
The problem is caused by new mechanism used in BEAST 2.7. The package `picocli` that lphybeast depends on has this code:

```java
        static Class<?> GROOVY_CLOSURE_CLASS = loadClosureClass();
        private static Class<?> loadClosureClass() {
            try { return Class.forName("groovy.lang.Closure"); }
            catch (Exception ignored) { return null;}
        }
```

It was working in BEAST 2.6 when everything were loaded into class path.

**Comment by walterxie** [comment]
Setting `-Dpicocli.disable.closures=true` using picocli:4.7.0 will stop picocli throwing `java.lang.NoClassDefFoundError: groovy.lang.Closure`
