### ISSUE TITLE
extension mechanism for LPhyBEAST to adapt with LPhy 

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/LPhyBeast#40]
Move *ToBEAST to the corresponding BEAST packages. 

1. develop a mechanism to register classes.
2. make an example, such as phylonco.

**Comment by walterxie** [comment]
The class registry are now relying on the implementation of `ClassesRegistry`, see example `LPhyBEASTRegistry`. The class path to locate all registry classes is hard coded to "lphybeast.registry". To avoid the name space conflict, the registry class name is required by naming as "package name" + "Registry" to make it unique.

The future improvement:
1. Remove the hard code to locate all registry classes. It will be robust, if the registry classes could be located under the package named as "beast_package_name.registry" naming convention. 
2. Make operators to be extendable.

**Comment by walterxie** [comment]
The 2nd version has no hard code for java package name to find registry classes. But it reply on the postfix "Registry.class" to filtered out some 3rd party classes that may cause trouble (e.g. NoClassDefFoundError).

**Comment by walterxie** [comment]
remove the condition on postfix to find registry class, but have to use BEASTClassLoader to avoid Java Error

**Comment by walterxie** [comment]
Use new method `PackageManager.find(ClassesRegistry.class, false)` to reduce the lines of code.

**Comment by walterxie** [comment]
Now the code has to depend on new version of BEAST >= 2.6.6

**Comment by walterxie** [comment]
It works with BEAST 2.6.6 or higher now. It will be a separated issue after BEAST 2.7 goes to the module system
